#!/bin/bash

set -o errexit

set -o nounset

worker_ready(){
    celery -A real_estate inspect ping
}

until worker_ready; do
    >&2 echo "Celery workers are not available...:-("
    sleep 1
done
>&2 echo "Celery workers are now available...:-)"

exec celery \
    -A real_estate flower \
    --broker="${CELERY_BROKER}" \
    --address=0.0.0.0 \
    --port=5555
